services:
  web:
    build: .
    container_name: bhuvanaweb
    ports:
      - "8000:80"

  webhook:
    build: ./webhook-server
    container_name: bhuvanaweb_webhook
    ports:
      - "9000:9000"
